#!/usr/bin/env python3
"""
Diff the current src/data/*.json against the most recent snapshot in
data/snapshots/, then:
  1. Save the new snapshot tagged with the current patch version
  2. Prepend a section to CHANGELOG.md describing what changed per nation

Run after build_data.py.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "src" / "data"
SNAPS = ROOT / "data" / "snapshots"
PATCH_JSON = ROOT / "data" / "patch.json"
CHANGELOG = ROOT / "CHANGELOG.md"

# Files we track for diffing
TRACKED = ["nations.json"]


def load_patch_meta() -> dict:
    if PATCH_JSON.exists():
        return json.loads(PATCH_JSON.read_text())
    return {"version": "unknown", "syncedAt": datetime.now(timezone.utc).isoformat()}


def load_current() -> dict[str, list | dict]:
    return {f: json.loads((DATA_DIR / f).read_text()) for f in TRACKED if (DATA_DIR / f).exists()}


def load_previous() -> tuple[str | None, dict[str, list | dict]]:
    """Return (version, data) for the most recent snapshot, or (None, {})."""
    if not SNAPS.exists():
        return None, {}
    snaps = sorted([p for p in SNAPS.iterdir() if p.is_dir()])
    if not snaps:
        return None, {}
    latest = snaps[-1]
    data = {}
    for f in TRACKED:
        p = latest / f
        if p.exists():
            data[f] = json.loads(p.read_text())
    return latest.name, data


def index_by_id(items: list[dict], key: str = "id") -> dict[str, dict]:
    return {it[key]: it for it in items if key in it}


def diff_nations(prev: list[dict], cur: list[dict]) -> list[str]:
    """Return human-readable bullet lines describing changes."""
    p = index_by_id(prev)
    c = index_by_id(cur)
    lines: list[str] = []

    added = sorted(set(c) - set(p))
    removed = sorted(set(p) - set(c))
    for nid in added:
        lines.append(f"- ➕ **{c[nid]['name']}** added")
    for nid in removed:
        lines.append(f"- ➖ **{p[nid]['name']}** removed")

    for nid in sorted(set(p) & set(c)):
        diffs = diff_dict(p[nid], c[nid], path=c[nid]["name"])
        lines.extend(diffs)
    return lines


def diff_dict(p: dict, c: dict, path: str) -> list[str]:
    out: list[str] = []
    keys = sorted(set(p) | set(c))
    for k in keys:
        pv, cv = p.get(k), c.get(k)
        if pv == cv:
            continue
        if isinstance(pv, list) and isinstance(cv, list):
            added = [x for x in cv if x not in pv]
            removed = [x for x in pv if x not in cv]
            for a in added:
                out.append(f"- 🟢 **{path}** · `{k}` added: {fmt(a)}")
            for r in removed:
                out.append(f"- 🔴 **{path}** · `{k}` removed: {fmt(r)}")
        elif isinstance(pv, dict) and isinstance(cv, dict):
            out.extend(diff_dict(pv, cv, f"{path} · {k}"))
        else:
            out.append(f"- ✏️ **{path}** · `{k}`: `{fmt(pv)}` → `{fmt(cv)}`")
    return out


def fmt(v) -> str:
    if isinstance(v, dict):
        return ", ".join(f"{k}={fmt(vv)}" for k, vv in sorted(v.items()))
    s = str(v)
    return s if len(s) < 80 else s[:77] + "..."


def save_snapshot(version: str, data: dict[str, list | dict]) -> Path:
    snap = SNAPS / version
    snap.mkdir(parents=True, exist_ok=True)
    for f, content in data.items():
        (snap / f).write_text(json.dumps(content, indent=2, sort_keys=True, ensure_ascii=False) + "\n")
    return snap


def prepend_changelog(version: str, ts: str, lines: list[str]) -> None:
    header = f"## {version} — {ts}\n\n"
    body = "\n".join(lines) if lines else "_No data changes._"
    block = header + body + "\n\n"

    if CHANGELOG.exists():
        existing = CHANGELOG.read_text()
        # Drop existing entry for the same version (re-runs replace, don't stack)
        # Match "## <version> — " section through to next "## " or EOF
        marker = f"\n## {version} —"
        if marker in existing:
            head, _, rest = existing.partition(marker)
            # find end (next section)
            next_section = rest.find("\n## ")
            if next_section >= 0:
                existing = head + rest[next_section + 1:]
            else:
                existing = head.rstrip() + "\n"
    else:
        existing = "# Changelog\n\nGenerated by `scripts/changelog.py`. Each entry diffs the canonical data against the previous patch snapshot.\n\n"

    # Insert below top heading
    if existing.startswith("# Changelog"):
        head, _, tail = existing.partition("\n")
        # find first blank line after the intro paragraph
        parts = tail.split("\n\n", 2)
        if len(parts) >= 2:
            intro = parts[0]
            body_after = "\n\n".join(parts[1:])
            new = f"{head}\n{intro}\n\n{block}{body_after}".rstrip() + "\n"
        else:
            new = f"{head}\n{tail}\n{block}".rstrip() + "\n"
    else:
        new = block + existing

    CHANGELOG.write_text(new)


def main() -> int:
    meta = load_patch_meta()
    version = meta.get("version", "unknown")
    ts = meta.get("syncedAt", datetime.now(timezone.utc).isoformat())

    cur = load_current()
    prev_version, prev = load_previous()

    lines: list[str] = []
    if not prev:
        lines.append(f"- 🌱 Initial snapshot — {len(cur.get('nations.json', []))} nations recorded.")
    else:
        for f in TRACKED:
            p, c = prev.get(f, []), cur.get(f, [])
            if f == "nations.json":
                lines.extend(diff_nations(p, c))

    snap = save_snapshot(version, cur)
    print(f"✓ snapshot: {snap.relative_to(ROOT)}")

    prepend_changelog(version, ts, lines)
    print(f"✓ changelog: {CHANGELOG.relative_to(ROOT)} — {len(lines)} change line(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main()) if False else __import__("sys").exit(main())
